GET http://localhost:3001/api/test/test

###

GET http://localhost:3001/api/users/test

###

GET http://localhost:3001/api/users/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImthbWkiLCJpYXQiOjE3MTEyODg1MzgsImV4cCI6MTcxMTI4OTQzOH0.nthGRxIR74_Iv39GxHQJj3kYaEpmDqRlefwmhmwozQc
###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "name": "testKami",
  "password": "Test25!!"
}

###
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6InRlc3RrYW1pIiwiaWF0IjoxNzExODAwODI2LCJleHAiOjE3MTE4MDE3MjZ9.NgO5TVDk_evqBdKzr_jJ6RJ6dsuP_moMmAwwi9OiQuo

POST http://localhost:3001/api/users/register
Content-Type: application/json

{
  "name": "kami",
  "email": "kamicron+kamiML@gmail.com",
  "password": "test25!!"
}

###

POST http://localhost:3001/api/users/logout
Content-Type: application/json

{
  "id": "3"
}

###

GET http://localhost:3001/api/carts/
Authorization: Bearer {{token}}
###

GET http://localhost:3001/api/carts/me
Authorization: Bearer {{token}}
###

@productId=8
@cartId=2
POST http://localhost:3001/api/carts/add-product
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": {{productId}},
  "cartId": {{cartId}}
}


###

@userId=3
@name="test"
@description="une description"
@category_id=2
@price=2
POST http://localhost:3001/api/producy/add-product
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user-id": {{userId}},
  "name": {{name}},
  "description": {{description}},
  "category_id": {{category_id}},
  "price": {{price}}

}


###