GET http://localhost:3001/api/test/test

###

GET http://localhost:3001/api/users/test

###

GET http://localhost:3001/api/users/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImthbWkiLCJpYXQiOjE3MTEyODg1MzgsImV4cCI6MTcxMTI4OTQzOH0.nthGRxIR74_Iv39GxHQJj3kYaEpmDqRlefwmhmwozQc
###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "name": "kami",
  "password": "test25!!"
}

###

POST http://localhost:3001/api/users/register
Content-Type: application/json

{
  "name": "kami",
  "email": "kamicron+kamiML@gmail.com",
  "password": "test25!!"
}

###

POST http://localhost:3001/api/users/logout
Content-Type: application/json

{
  "id": "3"
}

###

GET http://localhost:3001/api/carts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6ImthbWkiLCJpYXQiOjE3MTEzNjk0MjgsImV4cCI6MTcxMTM3MDMyOH0.yEtafZqPqOU5HmQkimNk9Eglr7u7w4vOZP18A-wPfW8
###